var t9_pinyin_index = [
    {key: "2", index: "a"},
    {key: "3", index: "e"},
    //{key: "4", index: "i"},
    {key: "6", index: "o"},
    // {key: "8", index: "u"},
    // {key: "8", index: "v"},
    {key: "24", index: "ai"},
    {key: "26", index: "an"},
    {key: "26", index: "ao"},
    {key: "22", index: "ba"},
    {key: "24", index: "bi"},
    {key: "26", index: "bo"},
    {key: "28", index: "bu"},
    {key: "22", index: "ca"},
    {key: "23", index: "ce"},
    {key: "24", index: "ci"},
    {key: "28", index: "cu"},
    {key: "32", index: "da"},
    {key: "33", index: "de"},
    {key: "34", index: "di"},
    {key: "38", index: "du"},
    {key: "36", index: "en"},
    {key: "37", index: "er"},
    {key: "32", index: "fa"},
    {key: "36", index: "fo"},
    {key: "38", index: "fu"},
    {key: "42", index: "ha"},
    {key: "42", index: "ga"},
    {key: "43", index: "ge"},
    {key: "43", index: "he"},
    {key: "48", index: "gu"},
    {key: "48", index: "hu"},
    {key: "54", index: "ji"},
    {key: "58", index: "ju"},
    {key: "52", index: "ka"},
    {key: "53", index: "ke"},
    {key: "58", index: "ku"},
    {key: "52", index: "la"},
    {key: "53", index: "le"},
    {key: "54", index: "li"},
    {key: "58", index: "lu"},
    {key: "58", index: "lv"},
    {key: "62", index: "ma"},
    {key: "63", index: "me"},
    {key: "64", index: "mi"},
    {key: "66", index: "mo"},
    {key: "68", index: "mu"},
    {key: "62", index: "na"},
    {key: "63", index: "ne"},
    {key: "64", index: "ni"},
    {key: "68", index: "nu"},
    {key: "68", index: "nv"},
    {key: "68", index: "ou"},
    {key: "72", index: "pa"},
    {key: "74", index: "pi"},
    {key: "76", index: "po"},
    {key: "78", index: "pu"},
    {key: "74", index: "qi"},
    {key: "78", index: "qu"},
    {key: "73", index: "re"},
    {key: "74", index: "ri"},
    {key: "78", index: "ru"},
    {key: "72", index: "sa"},
    {key: "73", index: "se"},
    {key: "74", index: "si"},
    {key: "78", index: "su"},
    {key: "82", index: "ta"},
    {key: "83", index: "te"},
    {key: "84", index: "ti"},
    {key: "88", index: "tu"},
    {key: "92", index: "wa"},
    {key: "96", index: "wo"},
    {key: "98", index: "wu"},
    {key: "94", index: "xi"},
    {key: "98", index: "xu"},
    {key: "92", index: "ya"},
    {key: "93", index: "ye"},
    {key: "94", index: "yi"},
    {key: "96", index: "yo"},
    {key: "98", index: "yu"},
    {key: "92", index: "za"},
    {key: "93", index: "ze"},
    {key: "94", index: "zi"},
    {key: "98", index: "zu"},
    {key: "264", index: "ang"},
    {key: "224", index: "bai"},
    {key: "226", index: "ban"},
    {key: "226", index: "bao"},
    {key: "234", index: "bei"},
    {key: "236", index: "ben"},
    {key: "243", index: "bie"},
    {key: "246", index: "bin"},
    {key: "224", index: "cai"},
    {key: "226", index: "can"},
    {key: "226", index: "cao"},
    {key: "242", index: "cha"},
    {key: "243", index: "che"},
    {key: "244", index: "chi"},
    {key: "248", index: "chu"},
    {key: "268", index: "cou"},
    {key: "284", index: "cui"},
    {key: "286", index: "cun"},
    {key: "286", index: "cuo"},
    {key: "324", index: "dai"},
    {key: "326", index: "dan"},
    {key: "326", index: "dao"},
    {key: "343", index: "die"},
    {key: "348", index: "diu"},
    {key: "368", index: "dou"},
    {key: "384", index: "dui"},
    {key: "386", index: "dun"},
    {key: "386", index: "duo"},
    {key: "326", index: "fan"},
    {key: "334", index: "fei"},
    {key: "336", index: "fen"},
    {key: "368", index: "fou"},
    {key: "424", index: "gai"},
    {key: "426", index: "gan"},
    {key: "426", index: "gao"},
    {key: "434", index: "gei"},
    {key: "436", index: "gen"},
    {key: "468", index: "gou"},
    {key: "482", index: "gua"},
    {key: "484", index: "gui"},
    {key: "486", index: "gun"},
    {key: "486", index: "guo"},
    {key: "423", index: "hai"},
    {key: "426", index: "han"},
    {key: "426", index: "hao"},
    {key: "434", index: "hei"},
    {key: "436", index: "hen"},
    {key: "468", index: "hou"},
    {key: "482", index: "hua"},
    {key: "484", index: "hui"},
    {key: "486", index: "hun"},
    {key: "486", index: "huo"},
    {key: "542", index: "jia"},
    {key: "543", index: "jie"},
    {key: "546", index: "jin"},
    {key: "548", index: "jiu"},
    {key: "583", index: "jue"},
    {key: "586", index: "jun"},
    {key: "524", index: "kai"},
    {key: "526", index: "kan"},
    {key: "526", index: "kao"},
    {key: "536", index: "ken"},
    {key: "568", index: "kou"},
    {key: "582", index: "kua"},
    {key: "584", index: "kui"},
    {key: "586", index: "kun"},
    {key: "586", index: "kuo"},
    {key: "524", index: "lai"},
    {key: "526", index: "lan"},
    {key: "526", index: "lao"},
    {key: "534", index: "lei"},
    {key: "543", index: "lie"},
    {key: "546", index: "lin"},
    {key: "548", index: "liu"},
    {key: "568", index: "lou"},
    {key: "583", index: "lue"},
    {key: "586", index: "lun"},
    {key: "586", index: "luo"},
    {key: "624", index: "mai"},
    {key: "626", index: "man"},
    {key: "626", index: "mao"},
    {key: "634", index: "mei"},
    {key: "636", index: "men"},
    {key: "643", index: "mie"},
    {key: "646", index: "min"},
    {key: "648", index: "miu"},
    {key: "668", index: "mou"},
    {key: "624", index: "nai"},
    {key: "626", index: "nan"},
    {key: "626", index: "nao"},
    {key: "634", index: "nei"},
    {key: "636", index: "nen"},
    {key: "643", index: "nie"},
    {key: "646", index: "nin"},
    {key: "648", index: "niu"},
    {key: "683", index: "nue"},
    {key: "686", index: "nuo"},
    {key: "724", index: "pai"},
    {key: "726", index: "pan"},
    {key: "726", index: "pao"},
    {key: "734", index: "pei"},
    {key: "736", index: "pen"},
    {key: "743", index: "pie"},
    {key: "746", index: "pin"},
    {key: "768", index: "pou"},
    {key: "742", index: "qia"},
    {key: "743", index: "qie"},
    {key: "746", index: "qin"},
    {key: "748", index: "qiu"},
    {key: "783", index: "que"},
    {key: "786", index: "qun"},
    {key: "726", index: "ran"},
    {key: "726", index: "rao"},
    {key: "736", index: "ren"},
    {key: "768", index: "rou"},
    {key: "784", index: "rui"},
    {key: "786", index: "run"},
    {key: "786", index: "ruo"},
    {key: "724", index: "sai"},
    {key: "726", index: "sao"},
    {key: "726", index: "san"},
    {key: "736", index: "sen"},
    {key: "742", index: "sha"},
    {key: "743", index: "she"},
    {key: "744", index: "shi"},
    {key: "748", index: "shu"},
    {key: "768", index: "sou"},
    {key: "784", index: "sui"},
    {key: "786", index: "sun"},
    {key: "786", index: "suo"},
    {key: "824", index: "tai"},
    {key: "826", index: "tan"},
    {key: "826", index: "tao"},
    {key: "843", index: "tie"},
    {key: "868", index: "tou"},
    {key: "884", index: "tui"},
    {key: "886", index: "tun"},
    {key: "886", index: "tuo"},
    {key: "924", index: "wai"},
    {key: "926", index: "wan"},
    {key: "934", index: "wei"},
    {key: "936", index: "wen"},
    {key: "942", index: "xia"},
    {key: "943", index: "xie"},
    {key: "946", index: "xin"},
    {key: "948", index: "xiu"},
    {key: "983", index: "xue"},
    {key: "986", index: "xun"},
    {key: "926", index: "yan"},
    {key: "926", index: "yao"},
    {key: "946", index: "yin"},
    {key: "968", index: "you"},
    {key: "983", index: "yue"},
    {key: "986", index: "yun"},
    {key: "924", index: "zai"},
    {key: "926", index: "zan"},
    {key: "926", index: "zao"},
    {key: "934", index: "zei"},
    {key: "936", index: "zen"},
    {key: "942", index: "zha"},
    {key: "943", index: "zhe"},
    {key: "944", index: "zhi"},
    {key: "948", index: "zhu"},
    {key: "968", index: "zou"},
    {key: "984", index: "zui"},
    {key: "986", index: "zun"},
    {key: "986", index: "zuo"},
    {key: "2264", index: "bang"},
    {key: "2364", index: "beng"},
    {key: "2426", index: "bian"},
    {key: "2426", index: "biao"},
    {key: "2464", index: "bing"},
    {key: "2264", index: "cang"},
    {key: "2364", index: "ceng"},
    {key: "2424", index: "chai"},
    {key: "2426", index: "chan"},
    {key: "2426", index: "chao"},
    {key: "2436", index: "chen"},
    {key: "2468", index: "chou"},
    {key: "2484", index: "chuai"},
    {key: "2484", index: "chui"},
    {key: "2484", index: "chun"},
    {key: "2486", index: "chuo"},
    {key: "2664", index: "cong"},
    {key: "2826", index: "cuan"},
    {key: "3264", index: "dang"},
    {key: "3364", index: "deng"},
    {key: "3426", index: "dian"},
    {key: "3426", index: "diao"},
    {key: "3464", index: "ding"},
    {key: "3664", index: "dong"},
    {key: "3826", index: "duan"},
    {key: "3264", index: "fang"},
    {key: "3364", index: "feng"},
    {key: "4264", index: "gang"},
    {key: "4364", index: "geng"},
    {key: "4664", index: "gong"},
    {key: "4824", index: "guai"},
    {key: "4826", index: "guan"},
    {key: "4264", index: "hang"},
    {key: "4364", index: "heng"},
    {key: "4664", index: "hong"},
    {key: "4823", index: "huai"},
    {key: "4826", index: "huan"},
    {key: "5426", index: "jian"},
    {key: "5426", index: "jiao"},
    {key: "5464", index: "jing"},
    {key: "5826", index: "juan"},
    {key: "5264", index: "kang"},
    {key: "5364", index: "keng"},
    {key: "5664", index: "kong"},
    {key: "5824", index: "kuai"},
    {key: "5826", index: "kuan"},
    {key: "5264", index: "lang"},
    {key: "5366", index: "leng"},
    {key: "5426", index: "lian"},
    {key: "5426", index: "liao"},
    {key: "5464", index: "ling"},
    {key: "5664", index: "long"},
    {key: "5826", index: "luan"},
    {key: "6264", index: "mang"},
    {key: "6364", index: "meng"},
    {key: "6426", index: "mian"},
    {key: "6426", index: "miao"},
    {key: "6464", index: "ming"},
    {key: "6264", index: "nang"},
    {key: "6364", index: "neng"},
    {key: "6426", index: "nian"},
    {key: "6426", index: "niao"},
    {key: "6464", index: "ning"},
    {key: "6664", index: "nong"},
    {key: "6826", index: "nuan"},
    {key: "7264", index: "pang"},
    {key: "7364", index: "peng"},
    {key: "7426", index: "pian"},
    {key: "7426", index: "piao"},
    {key: "7464", index: "ping"},
    {key: "7426", index: "qian"},
    {key: "7426", index: "qiao"},
    {key: "7464", index: "qing"},
    {key: "7826", index: "quan"},
    {key: "7264", index: "rang"},
    {key: "7364", index: "reng"},
    {key: "7664", index: "rong"},
    {key: "7826", index: "ruan"},
    {key: "7264", index: "sang"},
    {key: "7364", index: "seng"},
    {key: "7424", index: "shai"},
    {key: "7426", index: "shan"},
    {key: "7426", index: "shao"},
    {key: "7436", index: "shen"},
    {key: "7468", index: "shou"},
    {key: "7482", index: "shua"},
    {key: "7484", index: "shui"},
    {key: "7486", index: "shun"},
    {key: "7486", index: "shuo"},
    {key: "7664", index: "song"},
    {key: "7826", index: "suan"},
    {key: "8264", index: "tang"},
    {key: "8364", index: "teng"},
    {key: "8426", index: "tian"},
    {key: "8426", index: "tiao"},
    {key: "8464", index: "ting"},
    {key: "8664", index: "tong"},
    {key: "8826", index: "tuan"},
    {key: "9264", index: "wang"},
    {key: "9364", index: "weng"},
    {key: "9426", index: "xian"},
    {key: "9426", index: "xiao"},
    {key: "9464", index: "xing"},
    {key: "9826", index: "xuan"},
    {key: "9264", index: "yang"},
    {key: "9464", index: "ying"},
    {key: "9664", index: "yong"},
    {key: "9826", index: "yuan"},
    {key: "9264", index: "zang"},
    {key: "9364", index: "zeng"},
    {key: "9424", index: "zhai"},
    {key: "9426", index: "zhan"},
    {key: "9426", index: "zhao"},
    {key: "9436", index: "zhen"},
    {key: "9468", index: "zhou"},
    {key: "9482", index: "zhua"},
    {key: "9484", index: "zhui"},
    {key: "9486", index: "zhun"},
    {key: "9486", index: "zhuo"},
    {key: "9664", index: "zong"},
    {key: "9826", index: "zuan"},
    {key: "24264", index: "chang"},
    {key: "24364", index: "cheng"},
    {key: "24664", index: "chong"},
    {key: "24826", index: "chuan"},
    {key: "48264", index: "guang"},
    {key: "48264", index: "huang"},
    {key: "54264", index: "jiang"},
    {key: "54664", index: "jiong"},
    {key: "58264", index: "kuang"},
    {key: "54264", index: "liang"},
    {key: "64264", index: "niang"},
    {key: "74264", index: "qiang"},
    {key: "74664", index: "qiong"},
    {key: "74264", index: "shang"},
    {key: "74364", index: "sheng"},
    {key: "74824", index: "shuai"},
    {key: "74826", index: "shuan"},
    {key: "94264", index: "xiang"},
    {key: "94664", index: "xiong"},
    {key: "94264", index: "zhang"},
    {key: "94364", index: "zheng"},
    {key: "94664", index: "zhong"},
    {key: "94824", index: "zhuai"},
    {key: "94826", index: "zhuan"},
    {key: "248264", index: "chuang"},
    {key: "748264", index: "shuang"},
    {key: "948264", index: "zhuang"}
]

var t9_pinyin_symbol = [
    '。',
    '？',
    '！',
    '，',
    '、',
    '；',
    '：',
    '“',
    '”',
    '‘',
    '’',
    '（',
    '）',
    '-',
    '.',
    '《',
    '》'
]

var t9_english_index  = [
    {key: '2', list:['A', 'B', 'C', 'a', 'b', 'c']},
    {key: '3', list:['D', 'E', 'F', 'd', 'e', 'f']},
    {key: '4', list:['G', 'H', 'I', 'g', 'h', 'i']},
    {key: '5', list:['J', 'K', 'L', 'j', 'k', 'l']},
    {key: '6', list:['M', 'N', 'O', 'm', 'n', 'o']},
    {key: '7', list:['P', 'Q', 'R', 'S', 'p', 'q', 'r', 's']},
    {key: '8', list:['T', 'U', 'V', 't', 'u', 'v']},
    {key: '9', list:['W', 'X', 'Y', 'Z', 'w', 'x', 'y', 'z']},
]

var t9_english_symbol = [
    '.',
    '-',
    '_',
    '+',
    "=",    
    '!',
    '~',
    '`',    
    '@',
    '#',
    '$',
    '%',
    '^',
    '&',
    '*',
    '(',
    ')',
    '{',
    '}',
    '[',
    ']',
    ':',
    ';',
    '"',
    '\'',
    '<',
    '>',
    ',',
    '?',
    '/',
    '|'
]


function t9_get_pinyin_index (numstr) {
    var reg = /^\d*$/
    var indexs = []

    if (reg.test(numstr)) {
        for (var i = 0; i < t9_pinyin_index.length; i++) {
            if (t9_pinyin_index[i].key.indexOf(numstr) == 0){
                indexs.push(t9_pinyin_index[i].index)                
            }
        }
    }

    return indexs;
}

function t9_get_english_index(num) {
    for (var i = 0; i < t9_english_index.length; i++) {
        if (t9_english_index[i].key == num){
            return t9_english_index[i].list;
        }
    }    
}